# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Maven Plugin - CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '.github/workflows/ci.yml'
      - 'core/**'
      - 'plugin/**'
      - 'tests/**'
      - '**/pom.xml'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'core/**'
      - 'plugin/**'
      - 'tests/**'
      - '**/pom.xml'

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:

  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Validate Formatting
        run: |
          mvn -B validate -Pformat-check -Denforcer.skip=true

  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    needs: format-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          java-version: |
            11
            17
            21
          cache: 'maven'
          distribution: 'temurin'
      - name: Set up JDK 17
        if: matrix.java == '11'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: 'maven'
          distribution: 'temurin'
      - name: Build and Test on ${{ matrix.java }}
        run: mvn clean install '-Dorg.jboss.logmanager.nocolor=true' '-Djava11.home=${{ env.JAVA_HOME_11_X64 }}' '-Djava17.home=${{ env.JAVA_HOME_17_X64 }}'
      - name: Upload surefire logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/'
      - name: Upload failsafe logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failsafe-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/failsafe-reports/'
      - name: Upload logs for failed run
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/*.log'